AppName/config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  
  
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about_me', to: 'pages#home'
  get 'contact', to: 'pages#home'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

AppName/app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], :title => "Gavin Thomas Portfolio", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:alert], :title => "Gavin Thomas Portfolio", sticky: false) %>
<% else flash[:notice] %>
  <%= js add_gritter(flash[:notice], :title => "Gavin Thomas Portfolio", sticky: false) %>
<% end %>

AppName/app/views/shared/_app_footer.html.erb
<div class="mastfoot">
      <%= render 'shared/shield' %>
</div>

AppName/app/views/shared/_application_nav.html.erb
<div class="app-nav">
<div class="masthead clearfix">
  <div class="inner">
    
    <nav class="nav nav-masthead app-nav">
        <%= nav_helper 'nav-link', 'span' %>
        <%= login_helper 'nav-link' %>
    </nav>
    <h5 class="gav-t">Gavin Thomas</h5>
  </div>
  </div>
</div>

AppName/app/views/shared/_blog_footer.html.erb
        <footer class="blog-footer">
          <p>
            <%= copyright_generator %>
            <%= render 'shared/shield' %>
          </p>
          </p>
        </footer>

AppName/app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
    
     <a href="javascript:" id="return-to-top"><i class="icon-chevron-up"></i></i></a>
      
      
            <!-- ICON NEEDS FONT AWESOME FOR CHEVRON UP ICON -->
     <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    
     <script>
        $(window).scroll(function() {
          if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
              $('#return-to-top').fadeIn(400);    // Fade in the arrow
          } else {
              $('#return-to-top').fadeOut(200);   // Else fade out the arrow
          }
        });
        $('#return-to-top').click(function() {      // When arrow is clicked
            $('body,html').animate({
                scrollTop : 0                       // Scroll to top of body
            }, 500);
        });
      </script>
  </div>
</div>

AppName/app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Gavin Thomas", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

AppName/app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About Me</h4>
    <p>I am 15 years old and just recently started coding. I really enjoy it and this is my first real project</p>
  </div>

 <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>


  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/sneakysquidd"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.instagram.com/gavinthom.s/?hl=en"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://twitter.com/_Gavin_Thomas"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.facebook.com/profile.php?id=100020405670637"><%= fa_icon "facebook-square" %></a></li>
    </ol>
  </div>
</div>

AppName/app/views/shared/_nav.html.erb
<div class="<%= location %>"> 
 <%= link_to "Home", root_path %>
 <%= link_to "About Me", about_me_path %>
 <%= link_to "Contact", contact_path %>
 <%= link_to "Blog", blogs_path %>
 <%= link_to "Portfolio", portfolios_path %>

 
 

AppName/app/views/shared/_portfolio_footer.html.erb
<script src="/js/jquery-1.3.2.min.js" type="text/javascript"></script>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">


<script language="javascript">
                /*Scroll to top when arrow up clicked BEGIN*/
      $(window).scroll(function() {
          var height = $(window).scrollTop();
      });
      $(document).ready(function() {
          $("#back2Top").click(function(event) {
              event.preventDefault();
              $("html, body").animate({ scrollTop: 0 }, "slow");
              return false;
          });
      
      });
 /*Scroll to top when arrow up clicked END*/
</script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View All Portfolio Items', portfolios_path %> /
      <%= link_to 'Find Out More About Me', about_me_path %>
    </p>
    <p>
      <%= copyright_generator %> 
      <%= render 'shared/shield' %>
    </p>
  </div>
</footer>

AppName/app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">My name is Gavin Thomas and here is a portfolio of the things I have created</p>
    
    <p>
      <%= link_to 'Find out more about me', root_path, class: 'btn btn---border btn---primary btn---animated' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn--border btn--primary btn--animated' %>
    </p>
    
    
    
          <!-- Return to Top -->
            <a href="javascript:" id="return-to-top"><i class="icon-chevron-up"></i></i></a>
      
      
            <!-- ICON NEEDS FONT AWESOME FOR CHEVRON UP ICON -->
            <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
          </p>
        </div>
      </section>
      
      <script>
        $(window).scroll(function() {
          if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
              $('#return-to-top').fadeIn(200);    // Fade in the arrow
          } else {
              $('#return-to-top').fadeOut(200);   // Else fade out the arrow
          }
        });
        $('#return-to-top').click(function() {      // When arrow is clicked
            $('body,html').animate({
                scrollTop : 0                       // Scroll to top of body
            }, 500);
        });
      </script>
  </div>
</section>

AppName/app/views/shared/_portfolio_nav.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="collapse-navbar">
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Do you want to learn more about me? Below are portfolios of things I have created with coding.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Gavin Thomas</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

AppName/app/views/shared/_shield.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<i class="fa fa-shield"></i>